server:
  port: 8086

spring:
  dubbo:
    server: true
    provider:
      filter: dubboFilter
    monitor:
      protocol: registry
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Provide
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。<!-- 多注册中心配置，竖号分隔表示同时连接多个不同注册中心，同一注册中心的多个集群地址用逗号分隔 -->
      address: zookeeper://127.0.0.1:2181
      #register: false #只订阅，而不注册正在开发的服务，通过直连测试正在开发的服务
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    scan: com.Guoz.Dubbo.Service #服务暴露与发现消费所在的package
    service:
      loadbalance: roundrobin


